// Mock data for testing without live API calls
// NOTE: All data below is entirely synthetic and for demonstration purposes only.
export const mockAnalystResponse: any = {
  sql: {
    success: true,
    analyst: {
      message: {
        role: 'analyst',
        content: [
          {
            type: 'text',
            text: 'This is our interpretation of your question:\n\nWhich partners had the highest engagement scores in calendar year 2024 and what were their revenue contributions? This analysis will look at monthly engagement scores and revenue data for 2024.',
          },
          {
            type: 'sql',
            statement:
              'WITH __fact_partner_monthly_metrics AS (\n  SELECT\n    partner_id,\n    engagement_score,\n    month_date_key,\n    revenue\n  FROM your_database.your_schema.fact_partner_monthly_metrics\n), __dim_partner AS (\n  SELECT\n    name,\n    partner_id\n  FROM your_database.your_schema.dim_partner\n), __dim_date AS (\n  SELECT\n    date_key,\n    year\n  FROM your_database.your_schema.dim_date\n)\nSELECT\n  fpmm.partner_id,\n  dp.name,\n  MAX(fpmm.engagement_score) AS highest_engagement_score,\n  SUM(fpmm.revenue) AS total_revenue_contribution\nFROM __fact_partner_monthly_metrics AS fpmm\nLEFT OUTER JOIN __dim_partner AS dp\n  ON fpmm.partner_id = dp.partner_id\nLEFT OUTER JOIN __dim_date AS dd\n  ON fpmm.month_date_key = dd.date_key\nWHERE\n  dd.year = 2024\nGROUP BY\n  fpmm.partner_id,\n  dp.name\nORDER BY\n  highest_engagement_score DESC NULLS LAST\n -- Generated by Cortex Analyst\n;',
            confidence: {
              verified_query_used: null,
            },
          },
        ],
      },
      request_id: 'mock-request-id-example',
      warnings: [],
      semantic_model_selection: null,
      response_metadata: {
        is_semantic_sql: false,
        model_names: ['llm-model'],
        cortex_search_retrieval: [],
        question_category: 'CLEAR_SQL',
        analyst_orchestration_path: 'regular_sqlgen',
        analyst_latency_ms: 5553,
      },
    },
    sql: 'WITH __fact_partner_monthly_metrics AS (\n  SELECT\n    partner_id,\n    engagement_score,\n    month_date_key,\n    revenue\n  FROM your_database.your_schema.fact_partner_monthly_metrics\n), __dim_partner AS (\n  SELECT\n    name,\n    partner_id\n  FROM your_database.your_schema.dim_partner\n), __dim_date AS (\n  SELECT\n    date_key,\n    year\n  FROM your_database.your_schema.dim_date\n)\nSELECT\n  fpmm.partner_id,\n  dp.name,\n  MAX(fpmm.engagement_score) AS highest_engagement_score,\n  SUM(fpmm.revenue) AS total_revenue_contribution\nFROM __fact_partner_monthly_metrics AS fpmm\nLEFT OUTER JOIN __dim_partner AS dp\n  ON fpmm.partner_id = dp.partner_id\nLEFT OUTER JOIN __dim_date AS dd\n  ON fpmm.month_date_key = dd.date_key\nWHERE\n  dd.year = 2024\nGROUP BY\n  fpmm.partner_id,\n  dp.name\nORDER BY\n  highest_engagement_score DESC NULLS LAST\n -- Generated by Cortex Analyst\n;',
    columns: [
      'PARTNER_ID',
      'NAME',
      'HIGHEST_ENGAGEMENT_SCORE',
      'TOTAL_REVENUE_CONTRIBUTION',
    ],
    rows: [
      {
        PARTNER_ID: 'partner_alpha',
        NAME: 'Partner Alpha',
        HIGHEST_ENGAGEMENT_SCORE: '99',
        TOTAL_REVENUE_CONTRIBUTION: '114617258.26',
      },
      {
        PARTNER_ID: 'partner_beta',
        NAME: 'Partner Beta',
        HIGHEST_ENGAGEMENT_SCORE: '99',
        TOTAL_REVENUE_CONTRIBUTION: '291809151.05',
      },
      {
        PARTNER_ID: 'partner_gamma',
        NAME: 'Partner Gamma',
        HIGHEST_ENGAGEMENT_SCORE: '99',
        TOTAL_REVENUE_CONTRIBUTION: '333790079.72',
      },
      {
        PARTNER_ID: 'partner_delta',
        NAME: 'Partner Delta',
        HIGHEST_ENGAGEMENT_SCORE: '94',
        TOTAL_REVENUE_CONTRIBUTION: '184645767.85',
      },
      {
        PARTNER_ID: 'partner_epsilon',
        NAME: 'Partner Epsilon',
        HIGHEST_ENGAGEMENT_SCORE: '93',
        TOTAL_REVENUE_CONTRIBUTION: '306464913.92',
      },
      {
        PARTNER_ID: 'partner_zeta',
        NAME: 'Partner Zeta',
        HIGHEST_ENGAGEMENT_SCORE: '93',
        TOTAL_REVENUE_CONTRIBUTION: '187962327.84',
      },
      {
        PARTNER_ID: 'partner_eta',
        NAME: 'Partner Eta',
        HIGHEST_ENGAGEMENT_SCORE: '92',
        TOTAL_REVENUE_CONTRIBUTION: '240190751.71',
      },
      {
        PARTNER_ID: 'partner_theta',
        NAME: 'Partner Theta',
        HIGHEST_ENGAGEMENT_SCORE: '92',
        TOTAL_REVENUE_CONTRIBUTION: '313122027.84',
      },
      {
        PARTNER_ID: 'partner_iota',
        NAME: 'Partner Iota',
        HIGHEST_ENGAGEMENT_SCORE: '90',
        TOTAL_REVENUE_CONTRIBUTION: '219187472.82',
      },
      {
        PARTNER_ID: 'partner_kappa',
        NAME: 'Partner Kappa',
        HIGHEST_ENGAGEMENT_SCORE: '88',
        TOTAL_REVENUE_CONTRIBUTION: '235220705.77',
      },
    ],
    conversationHistory: [
      {
        role: 'user',
        content: [
          {
            type: 'text',
            text: 'Which partners had the highest engagement scores in 2024 and what were their revenue contributions?',
          },
        ],
      },
      {
        role: 'analyst',
        content: [
          {
            type: 'text',
            text: 'This is our interpretation of your question:\n\nWhich partners had the highest engagement scores in calendar year 2024 and what were their revenue contributions? This analysis will look at monthly engagement scores and revenue data for 2024.',
          },
          {
            type: 'sql',
            statement:
              'WITH __fact_partner_monthly_metrics AS (\n  SELECT\n    partner_id,\n    engagement_score,\n    month_date_key,\n    revenue\n  FROM your_database.your_schema.fact_partner_monthly_metrics\n), __dim_partner AS (\n  SELECT\n    name,\n    partner_id\n  FROM your_database.your_schema.dim_partner\n), __dim_date AS (\n  SELECT\n    date_key,\n    year\n  FROM your_database.your_schema.dim_date\n)\nSELECT\n  fpmm.partner_id,\n  dp.name,\n  MAX(fpmm.engagement_score) AS highest_engagement_score,\n  SUM(fpmm.revenue) AS total_revenue_contribution\nFROM __fact_partner_monthly_metrics AS fpmm\nLEFT OUTER JOIN __dim_partner AS dp\n  ON fpmm.partner_id = dp.partner_id\nLEFT OUTER JOIN __dim_date AS dd\n  ON fpmm.month_date_key = dd.date_key\nWHERE\n  dd.year = 2024\nGROUP BY\n  fpmm.partner_id,\n  dp.name\nORDER BY\n  highest_engagement_score DESC NULLS LAST\n -- Generated by Cortex Analyst\n;',
            confidence: {
              verified_query_used: null,
            },
          },
        ],
      },
    ],
  },
};
